### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by vilasevic** [corymurphy/CertificateManager#12]
Hi,

First of all great initiative, secondly I've encountered a few issues.

Issue 1) Deployment failes due to line containing Import-DscResource -ModuleName 'xWebAdministration' -ModuleVersion '2.4.0.0', worked around by simply removing -Moduleversion parameter

Issue 2)
Application startup exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CertificateManager.Startup.ConfigureServices(IServiceCollection services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
Hosting environment: Production
Content root path: c:\Program Files\CertificateManager
Now listening on: http://localhost:14455
Application started. Press Ctrl+C to shut down.
Application is shutting down...

I have not managed to solve it, any ideas?

**Comment by corymurphy** [comment]
Hi, my apologies for the delayed response. I haven't had time to work on this project since I'm no longer in a windows environment. I don't have a solution for you, but I do want to return to this project at some point.

**Comment by vilasevic** [comment]
No worries I solved it :). Will post solution a bit later.

**Comment by corymurphy** [comment]
Hi! I'm not sure if this app is still useful to anyone, but I think I fixed the deployment issue, at least in my testing on server 2016. I updated the README with new instructions. There was one final step that I forget to mention, which is to navigate to the `/initial-setup` endpoint to get everything configured, and after that, it should restart and bring you to a login page. I thought I implemented an automatic redirect, but it seems like that's not the case. The release and deploy workflow is very outdated and it's not work that i'm proud of. 

There are many outstanding issues with the current state of the app, so I wouldn't recommend this in a production scenario at the moment. My plan is to rewrite this in Go and HTMX so it's a bit easier to maintain for anyone who is looking for a nice replacement for the retired server 2003 pki web app experience.

Thank you for your patience and interest in this hobby project of mine :heart: :smile:
